#ifdef RGB_MATRIX_ENABLE
// RM_MOD1
#define ENABLE_RGB_MATRIX_CUSTOM_CYCLE_ALL
// RM_MOD2
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
// RM_MOD4
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
// RM_MOD6
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// RM_MOD8
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#endif
