#ifdef RGB_MATRIX_ENABLE
// stock-like side LED behavior for SOLID_COLOR mode
//#define RGB_MATRIX_SOLID_COLOR_RAINBOW_SIDES
// RM_MOD1
#define ENABLE_RGB_MATRIX_CUSTOM_CYCLE_ALL
// RM_MOD2
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
// RM_MOD4
#define ENABLE_RGB_MATRIX_CUSTOM_CYCLE_LEFT_RIGHT
// stock-like side LED behavior
#ifdef ENABLE_RGB_MATRIX_CUSTOM_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_CUSTOM_CYCLE_LEFT_RIGHT_SIDES_RUN_SIDEWAYS
#endif // ENABLE_RGB_MATRIX_CUSTOM_CYCLE_LEFT_RIGHT
// RM_MOD6
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// RM_MOD8
#define ENABLE_RGB_MATRIX_CUSTOM_CYCLE_OUT_IN
#endif
