// Copyright 2025 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

// RAM saving measures

// provide placeholder serial number
// instead of having it be generated by a RAM-hungry function
// ~36 bytes saved
#define SERIAL_NUMBER "0"

// disable some unused functions
// Cherry MX Lock switch support
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
// oneshot keys
#define NO_ACTION_ONESHOT
// tapping keys
#define NO_ACTION_TAPPING

// I2C interface config
#define I2C_DRIVER I2CD0
#define I2C1_SCL_PIN A4
#define I2C1_SDA_PIN A5
#define I2C1_OPMODE OPMODE_I2C
#define I2C1_CLOCK_SPEED 400000

// RGB driver ICs config
// disable GPIO pin: P1.0 - connected directly to both chips' SDB pins
#define SLED1734X_SDB_PIN B0
// i2c address selection pins
// the one close to the MCU
#define SLED1734X_I2C_ADDRESS_1 SLED1734X_I2C_ADDRESS_GND
// the one in the space bar area
#define SLED1734X_I2C_ADDRESS_2 SLED1734X_I2C_ADDRESS_VDDIO
